"""add phone number

Revision ID: 65895c3ff1b8
Revises: 91f09013bfa0
Create Date: 2021-11-10 21:44:29.674618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65895c3ff1b8'
down_revision = '91f09013bfa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
